'use client'

import { useEffect, useMemo, useState } from 'react'
import { ArrowRight, BookOpen, Brain, Check, ChevronLeft, ChevronRight, Clock3, Heart, Leaf, Menu, Play, Quote, Sparkles, UserRound, Wind, X, Youtube } from 'lucide-react'

const insights = [
  { title: 'The Mystery of Parallel Universes', subtitle: 'Cosmology, Consciousness & Reality', duration: '52 min', color: 'bg-[#d9b49c]', video: 'https://www.youtube.com/embed/7pX4sYqNnL4' },
  { title: 'Mind, Time, Science & Consciousness', subtitle: 'David Eagleman in conversation', duration: '48 min', color: 'bg-[#9eaf9c]', video: 'https://www.youtube.com/embed/kbTgYqG8f4A' },
  { title: 'Psychic Powers & Consciousness', subtitle: 'Dr. Devi Shetty & Sadhguru', duration: '38 min', color: 'bg-[#b5a79f]', video: 'https://www.youtube.com/embed/1M4hH3Rz9oE' },
  { title: '1 Simple Way to Overcome Burnout', subtitle: 'Yale University Hosts Sadhguru', duration: '24 min', color: 'bg-[#d3a29b]', video: 'https://www.youtube.com/embed/0fL-pnX8i3M' },
]
const areas = [
  ['Stress & Burnout', 'Understand pressure and discover healthier ways to respond.', Wind], ['Mindfulness', 'Practices for clarity, awareness and a steadier day.', Leaf], ['Emotional Wellbeing', 'Build a more curious, compassionate relationship with emotion.', Heart], ['Focus & Productivity', 'Learn how attention and habits shape performance.', Brain], ['Sleep & Recovery', 'Explore rest, recovery and the rhythm of your wellbeing.', Sparkles], ['Self Awareness', 'Notice thoughts, behaviours and personal patterns.', UserRound],
]
const moods = ['Calm', 'Stressed', 'Focused', 'Tired', 'Overwhelmed', 'Positive']

export default function Page() {
  const [view, setView] = useState('home')
  const [menu, setMenu] = useState(false)
  const [mood, setMood] = useState('')
  const [reflected, setReflected] = useState(false)
  const [saved, setSaved] = useState<number[]>([])
  const [modal, setModal] = useState<number | null>(null)
  const [authMode, setAuthMode] = useState<'login' | 'signup'>('login')
  const [user, setUser] = useState(false)
  const [email, setEmail] = useState('')
  const [slide, setSlide] = useState(0)
  useEffect(() => { const s = window.localStorage.getItem('zenviora-saved'); if (s) setSaved(JSON.parse(s)) }, [])
  const toggleSave = (i: number) => { const next = saved.includes(i) ? saved.filter(x => x !== i) : [...saved, i]; setSaved(next); window.localStorage.setItem('zenviora-saved', JSON.stringify(next)) }
  const go = (next: string) => { setView(next); setMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  const activeInsights = useMemo(() => [insights[slide], insights[(slide + 1) % insights.length], insights[(slide + 2) % insights.length]], [slide])

  return <main className="min-h-screen bg-background text-foreground">
    <header className="sticky top-0 z-40 border-b border-border/70 bg-background/90 backdrop-blur-md"><div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-6 lg:px-10">
      <button onClick={() => go('home')} className="font-serif text-2xl font-semibold tracking-tight text-primary">Zenviora<span className="text-accent">.</span></button>
      <nav className="hidden items-center gap-8 md:flex">{[['Home','home'],['About','about'],['Wellbeing','wellbeing'],['Insights','insights'],['Resources','resources']].map(([label,id]) => <button key={id} onClick={() => go(id)} className={`text-sm transition-colors hover:text-primary ${view === id ? 'font-semibold text-primary' : 'text-muted-foreground'}`}>{label}</button>)}</nav>
      <div className="hidden items-center gap-3 md:flex"><button onClick={() => { setAuthMode('login'); go('auth') }} className="px-4 py-2 text-sm font-medium text-primary">Login</button><button onClick={() => { setAuthMode('signup'); go('auth') }} className="rounded-full bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground shadow-sm transition hover:-translate-y-0.5">Get Started</button></div>
      <button aria-label="Open menu" onClick={() => setMenu(!menu)} className="rounded-full p-2 text-primary md:hidden">{menu ? <X /> : <Menu />}</button>
    </div>{menu && <div className="flex flex-col gap-4 border-t border-border bg-background px-6 py-5 md:hidden">{[['Home','home'],['About','about'],['Wellbeing','wellbeing'],['Insights','insights'],['Resources','resources']].map(([label,id]) => <button className="text-left text-sm" key={id} onClick={() => go(id)}>{label}</button>)}<button onClick={() => { setAuthMode('login'); go('auth') }} className="text-left text-sm">Login</button></div>}</header>

    {view === 'home' && <>
      <section className="relative overflow-hidden"><div className="mx-auto grid max-w-7xl items-center gap-12 px-6 pb-20 pt-20 lg:grid-cols-[1.03fr_.97fr] lg:px-10 lg:pb-28 lg:pt-28"><div className="relative z-10"><div className="mb-6 flex items-center gap-3 text-xs font-semibold uppercase tracking-[.2em] text-accent"><span className="h-px w-10 bg-accent" />A calmer mind begins with understanding</div><h1 className="max-w-2xl font-serif text-5xl leading-[1.04] tracking-tight text-primary sm:text-7xl">Understand your mind.<br /><em className="font-normal text-accent">Transform</em> your wellbeing.</h1><p className="mt-7 max-w-lg text-lg leading-8 text-muted-foreground">Explore practical tools, expert insights and mindful resources designed to help you build a healthier relationship with your mind.</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => go('wellbeing')} className="group rounded-full bg-primary px-6 py-3.5 text-sm font-semibold text-primary-foreground transition hover:-translate-y-1">Explore Your Wellbeing <ArrowRight className="ml-2 inline size-4 transition group-hover:translate-x-1" /></button><button onClick={() => go('insights')} className="rounded-full border border-primary/20 px-6 py-3.5 text-sm font-semibold text-primary transition hover:bg-secondary">Explore Insights</button></div></div><div className="relative mx-auto h-[420px] w-full max-w-[500px] lg:h-[520px]"><div className="absolute inset-8 rounded-[48%] bg-secondary/80" /><div className="absolute left-1/2 top-1/2 h-72 w-44 -translate-x-1/2 -translate-y-1/2 rounded-[48%_48%_45%_45%] bg-primary shadow-2xl shadow-primary/20"><div className="absolute -left-12 top-20 h-36 w-24 -rotate-12 rounded-full border-b-2 border-primary bg-primary" /><div className="absolute -right-12 top-20 h-36 w-24 rotate-12 rounded-full border-b-2 border-primary bg-primary" /><div className="absolute left-1/2 top-12 h-20 w-20 -translate-x-1/2 rounded-full bg-[#d4a58f]" /></div><div className="absolute right-8 top-16 rounded-full border border-primary/20 bg-background/70 px-4 py-2 text-xs text-primary backdrop-blur">pause · notice · grow</div><div className="absolute bottom-16 left-2 rounded-full border border-primary/20 bg-background/70 px-4 py-2 text-xs text-primary backdrop-blur">space to reflect</div><div className="absolute left-8 top-8 text-4xl text-accent/70">✦</div><div className="absolute bottom-5 right-16 text-5xl text-primary/20">◌</div></div></div></section>
      <section className="border-y border-border bg-secondary/50"><div className="mx-auto grid max-w-7xl gap-8 px-6 py-8 sm:grid-cols-2 lg:grid-cols-4 lg:px-10">{[['Understand','Learn more about your emotions, thoughts and patterns.'],['Reflect','Create space for self-reflection and awareness.'],['Learn','Explore psychology, neuroscience and mindfulness.'],['Grow','Develop healthier habits for everyday life.']].map(([a,b]) => <div key={a}><h3 className="font-serif text-xl text-primary">{a}</h3><p className="mt-1 text-sm leading-6 text-muted-foreground">{b}</p></div>)}</div></section>
      <Why go={go} /><Wellbeing go={go} /><Insights activeInsights={activeInsights} slide={slide} setSlide={setSlide} saved={saved} toggleSave={toggleSave} setModal={setModal} /><Reflection mood={mood} setMood={setMood} reflected={reflected} setReflected={setReflected} /><Mindfulness /><Experts /><About go={go} /><CTA go={go} />
    </>}
    {view === 'about' && <AboutPage go={go} />}{view === 'wellbeing' && <WellbeingPage />}{view === 'insights' && <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><Insights activeInsights={insights} slide={slide} setSlide={setSlide} saved={saved} toggleSave={toggleSave} setModal={setModal} /></section>}{view === 'resources' && <Resources />}{view === 'auth' && <Auth mode={authMode} setMode={setAuthMode} email={email} setEmail={setEmail} onSuccess={() => { setUser(true); go('dashboard') }} />}{view === 'dashboard' && <Dashboard user={user} saved={saved} go={go} mood={mood} />}

    {modal !== null && <div role="dialog" aria-modal="true" aria-label="Video player" className="fixed inset-0 z-50 flex items-center justify-center bg-primary/70 p-4 backdrop-blur-sm"><div className="relative w-full max-w-4xl overflow-hidden rounded-3xl bg-background shadow-2xl"><button aria-label="Close video" onClick={() => setModal(null)} className="absolute right-4 top-4 z-10 rounded-full bg-background/90 p-2 text-primary"><X /></button><div className="aspect-video bg-primary"><iframe className="h-full w-full" src={insights[modal].video} title={insights[modal].title} allow="autoplay; encrypted-media" allowFullScreen /></div><div className="p-6"><p className="text-xs font-semibold uppercase tracking-widest text-accent">Now playing</p><h2 className="mt-2 font-serif text-2xl text-primary">{insights[modal].title}</h2></div></div></div>}
  </main>
}

function Why({go}:{go:(x:string)=>void}) { return <section className="mx-auto grid max-w-7xl gap-14 px-6 py-24 lg:grid-cols-2 lg:items-center lg:px-10"><div className="relative min-h-[410px] overflow-hidden rounded-[2rem] bg-primary p-8"><div className="absolute -right-20 -top-20 size-72 rounded-full border border-sage/30" /><div className="absolute -bottom-24 -left-20 size-80 rounded-full border border-sage/30" /><div className="relative flex h-full flex-col justify-between"><span className="text-7xl text-sage/80">“</span><div><div className="mb-4 h-px w-16 bg-accent" /><p className="max-w-xs font-serif text-3xl leading-tight text-primary-foreground">The quality of our attention shapes the quality of our life.</p><p className="mt-4 text-sm text-sage">A space to return to yourself.</p></div></div></div><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-accent">Why Zenviora?</p><h2 className="mt-4 font-serif text-4xl leading-tight text-primary sm:text-5xl">Your mind deserves attention too.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Modern life constantly demands our attention. Zenviora creates a space to slow down, understand what is happening within, and discover practical ways to support mental wellbeing.</p><div className="mt-8 grid gap-4 sm:grid-cols-2">{['Mental self-awareness','Mindfulness education','Science-backed insights','Practical resources'].map(x => <div className="flex items-center gap-3 text-sm font-medium text-primary" key={x}><span className="flex size-7 items-center justify-center rounded-full bg-secondary text-accent"><Check className="size-4" /></span>{x}</div>)}</div><button onClick={() => go('about')} className="mt-9 text-sm font-semibold text-primary underline decoration-accent decoration-2 underline-offset-8">Our approach <ArrowRight className="ml-2 inline size-4" /></button></div></section> }
function Wellbeing({go}:{go:(x:string)=>void}) { return <section className="bg-secondary/50 px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-6"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-accent">Find your starting point</p><h2 className="mt-3 font-serif text-4xl text-primary sm:text-5xl">Explore your wellbeing</h2></div><button onClick={() => go('wellbeing')} className="text-sm font-semibold text-primary">View all areas <ArrowRight className="ml-2 inline size-4" /></button></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{areas.map(([title,desc,Icon],i) => <article className="group rounded-2xl border border-border bg-background p-7 transition hover:-translate-y-1 hover:shadow-xl hover:shadow-primary/5" key={title as string}><Icon className="size-7 text-accent" /><h3 className="mt-7 font-serif text-2xl text-primary">{title as string}</h3><p className="mt-3 min-h-12 text-sm leading-6 text-muted-foreground">{desc as string}</p><button onClick={() => go('wellbeing')} className="mt-6 text-sm font-semibold text-primary">Explore <ArrowRight className="ml-1 inline size-4 transition group-hover:translate-x-1" /></button></article>)}</div></div></section> }
function WellbeingPage(){ return <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-accent">A gentle place to begin</p><h1 className="mt-4 max-w-2xl font-serif text-6xl text-primary">Explore your wellbeing.</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Choose a thread that feels relevant today. There is no right order, and no need to solve everything at once.</p><div className="mt-14 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{areas.map(([t,d,I]) => <article className="rounded-3xl bg-secondary/70 p-8" key={t as string}><I className="size-8 text-accent" /><h2 className="mt-8 font-serif text-3xl text-primary">{t as string}</h2><p className="mt-3 leading-7 text-muted-foreground">{d as string}</p><button className="mt-8 rounded-full bg-primary px-5 py-2.5 text-sm text-primary-foreground">Begin exploring <ArrowRight className="ml-2 inline size-4" /></button></article>)}</div></section> }
function Insights({activeInsights,slide,setSlide,saved,toggleSave,setModal}:{activeInsights:typeof insights,slide:number,setSlide:(n:number)=>void,saved:number[],toggleSave:(n:number)=>void,setModal:(n:number)=>void}) { return <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="flex items-end justify-between gap-6"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-accent">The Zenviora journal</p><h2 className="mt-3 font-serif text-4xl text-primary sm:text-5xl">Insights on mental wellbeing</h2><p className="mt-4 max-w-xl text-muted-foreground">Conversations and ideas from scientists, psychologists and thinkers.</p></div><div className="hidden gap-2 sm:flex"><button aria-label="Previous insights" onClick={() => setSlide((slide + insights.length - 1) % insights.length)} className="rounded-full border border-border p-3 text-primary"><ChevronLeft /></button><button aria-label="Next insights" onClick={() => setSlide((slide + 1) % insights.length)} className="rounded-full border border-border p-3 text-primary"><ChevronRight /></button></div></div><div className="mt-12 grid gap-6 md:grid-cols-3">{activeInsights.map((item,i) => <article key={item.title} className="group min-w-0"><button onClick={() => setModal((slide+i)%insights.length)} className={`relative block aspect-[1.35] w-full overflow-hidden rounded-2xl ${item.color}`}><div className="absolute inset-0 bg-[radial-gradient(circle_at_65%_35%,rgba(255,255,255,.55),transparent_24%),linear-gradient(125deg,transparent_40%,rgba(18,55,42,.28))]" /><span className="absolute left-5 top-5 rounded-full bg-background/80 px-3 py-1 text-xs font-semibold text-primary">Video</span><span className="absolute right-5 top-5 flex items-center gap-1 rounded-full bg-background/80 px-3 py-1 text-xs text-primary"><Clock3 className="size-3" />{item.duration}</span><span className="absolute bottom-5 left-5 flex size-12 items-center justify-center rounded-full bg-primary text-primary-foreground transition group-hover:scale-110"><Play className="ml-0.5 size-5 fill-current" /></span></button><button onClick={() => toggleSave((slide+i)%insights.length)} aria-label="Save insight" className="float-right mt-4 rounded-full p-2 text-accent"><Heart className={`size-5 ${saved.includes((slide+i)%insights.length) ? 'fill-current' : ''}`} /></button><h3 className="pt-4 font-serif text-2xl leading-tight text-primary">{item.title}</h3><p className="mt-2 text-sm font-semibold text-accent">{item.subtitle}</p><p className="mt-3 text-sm leading-6 text-muted-foreground">A thoughtful conversation exploring the mind, reality and the human experience.</p></article>)}</div></section> }
function Reflection({mood,setMood,reflected,setReflected}:{mood:string,setMood:(x:string)=>void,reflected:boolean,setReflected:(x:boolean)=>void}) { return <section className="px-6 py-24 lg:px-10"><div className="mx-auto max-w-5xl overflow-hidden rounded-[2rem] bg-primary p-8 text-primary-foreground sm:p-12 lg:p-16"><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-center"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-sage">Daily reflection</p><h2 className="mt-4 font-serif text-4xl leading-tight sm:text-5xl">Take a moment.</h2><p className="mt-5 leading-7 text-sage">You do not need to change how you feel. Just notice. This is a private, non-diagnostic space for checking in with yourself.</p></div><div className="rounded-2xl bg-primary-foreground/10 p-6 sm:p-8"><p className="font-serif text-2xl">How are you really feeling today?</p><div className="mt-6 flex flex-wrap gap-2">{moods.map(x => <button key={x} onClick={() => setMood(x)} className={`rounded-full border px-4 py-2 text-sm transition ${mood===x ? 'border-accent bg-accent text-primary-foreground' : 'border-sage/40 text-sage hover:border-sage'}`}>{x}</button>)}</div><button disabled={!mood} onClick={() => setReflected(true)} className="mt-7 rounded-full bg-background px-5 py-3 text-sm font-semibold text-primary disabled:cursor-not-allowed disabled:opacity-50">{reflected ? 'Reflection saved' : 'Reflect Now'} <ArrowRight className="ml-2 inline size-4" /></button>{reflected && <p className="mt-4 text-sm text-sage">Thank you for making space for yourself today.</p>}</div></div></div></section> }
function Mindfulness(){ return <section className="border-y border-border bg-secondary/40 px-6 py-24 lg:px-10"><div className="mx-auto max-w-7xl"><p className="text-sm font-semibold uppercase tracking-[.18em] text-accent">Mindful moments</p><h2 className="mt-3 font-serif text-4xl text-primary sm:text-5xl">Small moments can change your day.</h2><div className="mt-12 grid gap-5 lg:grid-cols-3">{[['Morning Awareness','Start your day with intention.','06 min'],['Breathing Space','Take a few minutes to slow down and reconnect.','04 min'],['Evening Reflection','End your day by noticing what mattered.','08 min']].map(([t,d,time],i)=><article key={t} className={`relative min-h-64 overflow-hidden rounded-3xl p-7 ${i===1?'bg-primary text-primary-foreground':'bg-background text-primary'}`}><div className="absolute -right-10 -top-10 size-40 rounded-full border border-current opacity-10" /><p className="text-xs font-semibold uppercase tracking-widest opacity-70">{time}</p><h3 className="mt-20 font-serif text-3xl">{t}</h3><p className="mt-2 text-sm opacity-70">{d}</p></article>)}</div></div></section> }
function Experts(){ return <section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-[.18em] text-accent">Many ways of knowing</p><h2 className="mt-3 font-serif text-4xl text-primary sm:text-5xl">Learn from different perspectives</h2></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{[['Psychology','How we think and feel'],['Neuroscience','The living brain'],['Mindfulness','Attention in practice'],['Consciousness','Questions within'],['Human Behavior','Patterns we share']].map(([x,y])=><div key={x} className="rounded-2xl border border-border p-6 text-center transition hover:border-accent hover:bg-secondary/50"><BookOpen className="mx-auto size-6 text-accent" /><h3 className="mt-5 font-serif text-xl text-primary">{x}</h3><p className="mt-2 text-xs text-muted-foreground">{y}</p></div>)}</div></section> }
function About({go}:{go:(x:string)=>void}) { return <section className="mx-auto grid max-w-7xl gap-12 px-6 py-24 lg:grid-cols-2 lg:px-10"><div><p className="text-sm font-semibold uppercase tracking-[.18em] text-accent">About Zenviora</p><h2 className="mt-3 font-serif text-4xl text-primary sm:text-5xl">Built around one simple idea.</h2><p className="mt-6 text-lg leading-8 text-muted-foreground">Wellbeing is not only about fixing problems. It is also about understanding ourselves, becoming more aware and creating space for healthier ways of living.</p></div><div className="flex flex-col justify-center gap-4">{['Educational content','Expert conversations','Mindfulness resources','Self-reflection tools','Wellbeing insights'].map(x=><button key={x} onClick={() => go('about')} className="flex items-center justify-between border-b border-border py-4 text-left font-serif text-xl text-primary"><span>{x}</span><ArrowRight className="size-5 text-accent" /></button>)}</div></section> }
function CTA({go}:{go:(x:string)=>void}) { return <section className="mx-6 mb-10 rounded-[2rem] bg-primary px-8 py-16 text-center text-primary-foreground lg:mx-10 lg:px-16"><h2 className="font-serif text-4xl sm:text-5xl">Give your mind a moment.</h2><p className="mx-auto mt-5 max-w-lg leading-7 text-sage">Explore ideas, practices and conversations that can help you understand yourself a little better.</p><div className="mt-8 flex justify-center gap-3"><button onClick={() => go('insights')} className="rounded-full bg-background px-5 py-3 text-sm font-semibold text-primary">Explore Zenviora</button><button onClick={() => go('dashboard')} className="rounded-full border border-sage/40 px-5 py-3 text-sm font-semibold text-sage">Start reflecting</button></div></section> }
function AboutPage({go}:{go:(x:string)=>void}){ return <><section className="mx-auto max-w-7xl px-6 py-24 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-accent">A different kind of wellbeing platform</p><h1 className="mt-5 max-w-3xl font-serif text-6xl leading-tight text-primary">More awareness.<br /><em className="font-normal text-accent">Less autopilot.</em></h1><p className="mt-8 max-w-xl text-lg leading-8 text-muted-foreground">Zenviora brings together thoughtful education, mindful practices and space for reflection—without telling you who to be.</p><button onClick={() => go('wellbeing')} className="mt-9 rounded-full bg-primary px-6 py-3 text-sm text-primary-foreground">Explore the areas <ArrowRight className="ml-2 inline size-4" /></button></section><div className="bg-secondary/50 px-6 py-20 lg:px-10"><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-3"><div><Quote className="size-8 text-accent" /><p className="mt-6 font-serif text-2xl text-primary">We create better lives by paying better attention.</p></div><p className="leading-8 text-muted-foreground md:col-span-2">Our approach is educational, human and practical. We invite curiosity rather than certainty, and small steps rather than perfect routines. Every resource is designed to help you pause, learn and choose what supports you.</p></div></div></> }
function Resources(){ return <section className="mx-auto max-w-7xl px-6 py-20 lg:px-10"><p className="text-sm font-semibold uppercase tracking-[.18em] text-accent">A library for your inner life</p><h1 className="mt-4 font-serif text-6xl text-primary">Resources for the everyday.</h1><div className="mt-14 grid gap-5 md:grid-cols-3">{['Guided practices','Reading room','Reflection prompts'].map((x,i)=><article className="rounded-3xl bg-secondary/60 p-8" key={x}><div className="flex size-12 items-center justify-center rounded-full bg-background text-accent">{i===0?<Wind />:i===1?<BookOpen />:<Sparkles />}</div><h2 className="mt-10 font-serif text-3xl text-primary">{x}</h2><p className="mt-3 leading-7 text-muted-foreground">Thoughtful, accessible ways to make a little more room for awareness.</p><button className="mt-8 text-sm font-semibold text-primary">Browse collection <ArrowRight className="ml-2 inline size-4" /></button></article>)}</div></section> }
function Auth({mode,setMode,email,setEmail,onSuccess}:{mode:'login'|'signup',setMode:(x:'login'|'signup')=>void,email:string,setEmail:(x:string)=>void,onSuccess:()=>void}) { return <section className="flex min-h-[calc(100vh-80px)] items-center justify-center px-6 py-16"><div className="w-full max-w-md"><div className="text-center"><p className="text-sm font-semibold uppercase tracking-widest text-accent">Welcome to Zenviora</p><h1 className="mt-4 font-serif text-5xl text-primary">{mode==='login'?'Welcome back.':'Begin your journey.'}</h1><p className="mt-4 text-muted-foreground">{mode==='login'?'Continue making space for what matters.':'Create a private space for reflection and learning.'}</p></div><div className="mt-10 rounded-3xl border border-border bg-background p-7 shadow-xl shadow-primary/5"><label className="text-sm font-medium text-primary">Email address</label><input value={email} onChange={e=>setEmail(e.target.value)} type="email" placeholder="you@example.com" className="mt-2 w-full rounded-xl border border-border bg-secondary/30 px-4 py-3 outline-none ring-accent focus:ring-2" /><label className="mt-5 block text-sm font-medium text-primary">Password</label><input type="password" placeholder="••••••••" className="mt-2 w-full rounded-xl border border-border bg-secondary/30 px-4 py-3 outline-none ring-accent focus:ring-2" /><button onClick={onSuccess} className="mt-6 w-full rounded-full bg-primary py-3.5 text-sm font-semibold text-primary-foreground">{mode==='login'?'Log in':'Create account'} <ArrowRight className="ml-2 inline size-4" /></button><button className="mt-4 w-full text-sm text-muted-foreground">Forgot password?</button><p className="mt-6 text-center text-sm text-muted-foreground">{mode==='login'?"New to Zenviora?":"Already have an account?"} <button onClick={()=>setMode(mode==='login'?'signup':'login')} className="font-semibold text-primary underline">{mode==='login'?'Create an account':'Log in'}</button></p></div><p className="mt-5 text-center text-xs leading-5 text-muted-foreground">Prototype mode: your account is simulated locally for this preview.</p></div></section> }
function Dashboard({user,saved,go,mood}:{user:boolean,saved:number[],go:(x:string)=>void,mood:string}){ return <section className="mx-auto max-w-7xl px-6 py-16 lg:px-10"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-semibold uppercase tracking-widest text-accent">Your space</p><h1 className="mt-3 font-serif text-5xl text-primary">Good morning{user?', friend':''}.</h1><p className="mt-3 text-muted-foreground">A little room to notice where you are.</p></div><button onClick={()=>go('home')} className="rounded-full border border-border px-5 py-2.5 text-sm text-primary">Back to explore</button></div><div className="mt-12 grid gap-5 lg:grid-cols-3"><div className="rounded-3xl bg-primary p-7 text-primary-foreground lg:col-span-2"><p className="text-xs font-semibold uppercase tracking-widest text-sage">Current reflection</p><h2 className="mt-10 font-serif text-3xl">{mood ? `Today you noticed feeling ${mood.toLowerCase()}.` : 'How are you arriving today?'}</h2><p className="mt-3 max-w-md text-sm leading-6 text-sage">Keep checking in with curiosity. There is no score to achieve.</p><button onClick={()=>go('home')} className="mt-8 rounded-full bg-background px-5 py-3 text-sm font-semibold text-primary">Reflect again <ArrowRight className="ml-2 inline size-4" /></button></div><div className="rounded-3xl border border-border p-7"><p className="text-xs font-semibold uppercase tracking-widest text-accent">Your rhythm</p><div className="mt-8 flex items-end gap-2">{[35,55,42,70,48,78,62].map((h,i)=><div key={i} className="flex-1 rounded-t-full bg-secondary" style={{height:`${h}px`}}><div className="h-1/2 rounded-full bg-sage" /></div>)}</div><p className="mt-4 text-sm text-muted-foreground">7 moments of reflection</p></div></div><div className="mt-5 grid gap-5 md:grid-cols-2"><div className="rounded-3xl border border-border p-7"><h2 className="font-serif text-2xl text-primary">Saved insights</h2><p className="mt-2 text-sm text-muted-foreground">{saved.length ? `${saved.length} conversations saved for later.` : 'Save a conversation that speaks to you.'}</p><button onClick={()=>go('insights')} className="mt-8 text-sm font-semibold text-primary">Explore insights <ArrowRight className="ml-2 inline size-4" /></button></div><div className="rounded-3xl border border-border p-7"><h2 className="font-serif text-2xl text-primary">Your history</h2><p className="mt-2 text-sm text-muted-foreground">Reflection entries will gather here as you return.</p><div className="mt-7 flex items-center gap-3 text-sm text-primary"><span className="flex size-8 items-center justify-center rounded-full bg-secondary text-accent"><Check className="size-4" /></span>Today · check-in complete</div></div></div></section> }

